import type { Metadata } from 'next';
import React from 'react';
import { Toaster } from 'sonner';

import { inter } from '@/app/fonts';
import { QueryProvider } from '@/components/providers/query-provider';

import '@/styles/index.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`h-full ${inter.variable}`} lang="zh-CN" suppressHydrationWarning>
      <body
        className="flex flex-col h-full antialiased"
        style={inter.style}
        suppressHydrationWarning
      >
        <QueryProvider>
          <main className="h-full">{children}</main>
        </QueryProvider>
        <Toaster
          position="top-center"
          duration={4000}
          style={{
            fontFamily:
              '-apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans SC", "Helvetica Neue", Arial, sans-serif',
          }}
          toastOptions={{
            style: {
              background: '#ffffff',
              border: '1px solid #e5e7eb',
              color: '#374151',
              width: 'auto',
              minWidth: 'unset',
              maxWidth: 'none',
              display: 'flex',
              alignItems: 'center',
            },
          }}
        />
      </body>
    </html>
  );
}
